default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: terminal_db
  username: terminal_user
  password: XXXXXX
  host: localhost

test:
  <<: *default
  database: XXXXXXXXX
  username: XXXXXXXXX
  password: XXXXXXXXX
  host: XXXXXXXXX

production:
  <<: *default
  database: XXXXXXXXX
  username: XXXXXXXXX
  password: XXXXXXXXX
  host: XXXXXXXXX

